# swagger.yml
swagger: "2.0"
info:
  title: Sample API
  description: This is a sample API with GET and POST methods.
  version: "1.0.0"
host: "localhost:5001"  # Change this to your actual web server URL
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /sample-get-api/{name}:
    get:
      summary: "Sample GET API (URL Parameter)"
      parameters:
        - name: "name"
          in: "path"
          required: true
          type: "string"
          description: "The name to greet."
      responses:
        200:
          description: "A greeting message."
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Hello John!"
  /sample-get-api-query:
    get:
      summary: "Sample GET API (Query Parameter)"
      parameters:
        - name: "name"
          in: "query"
          required: true
          type: "string"
          description: "The name to greet."
      responses:
        200:
          description: "A greeting message."
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Hello John!"
  /sample-post-api:
    post:
      summary: "Sample POST API"
      parameters:
        - name: "data"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                example: "John Doe"
      responses:
        200:
          description: "A confirmation message."
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "success"
              message:
                type: "string"
                example: "Received John Doe"
